FROM ubuntu:22.04
RUN sed -i 's@archive.ubuntu.com@mirrors.aliyun.com@g' /etc/apt/sources.list && apt-get update && apt-get install -y openssh-server openjdk-8-jdk wget curl tar vim net-tools iputils-ping && rm -rf /var/lib/apt/lists/*
RUN mkdir /var/run/sshd && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "root:123456" | chpasswd
RUN useradd -m -s /bin/bash learner && echo "learner:123456" | chpasswd
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
